[theme]
primaryColor = "#004aad"          # Cor dos botões e destaques
backgroundColor = "#ffffff"       # Cor do fundo da página
secondaryBackgroundColor = "#f0f2f6" # Cor das caixas de entrada e barra lateral
textColor = "#262730"             # Cor das letras
font = "sans serif"               # Opções: "sans serif", "serif" ou "monospace"